swagger: '2.0'

info:
  version: "1.0.0"
  title: 'KMDP Endpoint Monitoring API'
  license:
    name: Apache License, Version 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  description: |
    Reusable module that can be implemented for Java products using Spring to consolidate like code and surface the health endpoints (health, state, version) within any Java Spring implementation.
tags:
  - name: Health
    description: |
      Return information about the application including schema version, status, system, version, environment, and components.

  - name: Version
    description: |
      Return the version of the application.

  - name: State
    description: |
      Return the state of the application including schema version, environment, and features.

produces:
  - application/json

paths:

  ####################################################################################################
  # Health
  ####################################################################################################

  /health:
    get:
      tags:
        - Health
      summary: Display the health of the application.
      description: |
        Return information about the application including schema version, status, system, version, environment, and components.
      operationId: getHealthData
      produces:
        - application/json
      responses:
        200:
          description: |
            A list of application information detailing the status of the system.
          schema:
            $ref: '#/definitions/HealthData'
        500:
          description: |
            Unable to determine the health of the application.
        501:
          description: |
            This endpoint has not been implemented for this application.

  ####################################################################################################
  # Version
  ####################################################################################################

  /version:
    get:
      tags:
        - Version
      summary: Display the version of the application.
      description: |
        Return the version of the application
      operationId: getVersionData
      produces:
        - application/json
      responses:
        200:
          description: |
            The version of the application
          schema:
            $ref: '#/definitions/VersionData'
        500:
          description: |
            Unable to determine the version of the application.
        501:
          description: |
            This endpoint has not been implemented for this application.

  ####################################################################################################
  # State
  ####################################################################################################

  /state:
    get:
      tags:
        - State
      summary: Display the state of the application.
      description: |
        Return information about the application state
      operationId: getStateData
      produces:
        - application/json
      responses:
        200:
          description: |
            A list of application information detailing the state of the system.
          schema:
            $ref: '#/definitions/StateData'
        500:
          description: |
            Unable to determine the state of the application.
        501:
          description: |
            This endpoint has not been implemented for this application.

####################################################################################################

definitions:
  HealthData:
    description: The health endpoint schema
    type: object
    properties:
      version:
        $ref: '#/definitions/version'
      deploymentEnvironment:
        $ref: '#/definitions/deploymentEnvironment'
      serviceUrl:
        $ref: '#/definitions/serviceUrl'
      components:
        $ref: '#/definitions/components'

  VersionData:
    description: The version endpoint schema
    type: object
    required:
      - version
    properties:
      version:
        $ref: '#/definitions/version'

  StateData:
    description: The state endpoint schema
    type: object
    properties:
      buildProps:
        $ref: '#/definitions/buildProps'
      systemInfo:
        $ref: '#/definitions/systemInfo'
      implementationStrategy:
        $ref: '#/definitions/implementationStrategy'
      serviceNow:
        $ref: '#/definitions/serviceNow'

  status:
    description: The primary signal as to the health of the service or application.
    type: string
    enum:
      - Up
      - Down
      - Impaired

  serviceNow:
    type: object
    properties:
      id:
        pattern: CI*
        description: The ServiceNow configuration item ID
        type: string
      url:
        description: The ServiceNow configuration item URI
        type: string
      display:
        description: A human-readable display name for the system
        type: string

  buildProps:
    type: object
    additionalProperties:
      type: string

  systemInfo:
    type: object
    additionalProperties:
      type: string

  implementationStrategy:
    type: object
    additionalProperties:
      type: string

  version:
    description: The current version of the system
    type: string

  deploymentEnvironment:
    description: The current application environment
    type: string
    enum:
      - dev
      - test
      - int
      - uat
      - local
      - prod
      - unknown

  serviceUrl:
    type: object
    properties:
      url:
        type: string
      status:
        $ref: '#/definitions/status'

  components:
    type: object
    additionalProperties:
      $ref: '#/definitions/element'

  element:
    type: object
    additionalProperties:
      type: string